name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  suite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']

    name: 'PHP ${{ matrix.php-versions }} test suite'
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run style checks
        run: vendor/bin/phpcs --standard=psr2 src/

      - name: Run Unit tests
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

      - name: Upload coverage to Codecov
      - uses: codecov/codecov-action@v1
